### ISSUE TITLE
TypeError: invalid file: PosixPath('tmp/grid-0.jpg')

### ISSUE THREAD

**Issue by wwwins** [wwwins/ImageGridPython#2]
Traceback (most recent call last):
  File "upload_photo_grid.py", line 29, in <module> api.uploadPhoto(fn)
  File "/home/pi/Instagram-API-python/InstagramAPI/InstagramAPI.py", line 151, in uploadPhoto
    'photo': ('pending_media_%s.jpg' % upload_id, open(photo, 'rb'), 'application/octet-stream', {'Content-Transfer-Encoding': 'binary'})}
TypeError: invalid file: PosixPath('tmp/grid-0.jpg')

**Comment by wwwins** [comment]
Just convert the object to a string:
`api.uploadPhoto(str(fn))`
