### ISSUE TITLE
KeyError: 274

### ISSUE THREAD

**Issue by wwwins** [wwwins/ImageGridPython#3]
Traceback (most recent call last):
  File "upload_photo_grid.py", line 26, in <module> for fn in imageGrid.saveGrid(image_fn, div_x, div_y):
  File "/home/pi/.virtualenvs/py3/lib/python3.4/site-packages/imageGrid/imageGrid.py", line 124, in saveGrid
    img = rotateByOrientation(img)
  File "/home/pi/.virtualenvs/py3/lib/python3.4/site-packages/imageGrid/imageGrid.py", line 82, in rotateByOrientation
    o = getOrientation(image)
  File "/home/pi/.virtualenvs/py3/lib/python3.4/site-packages/imageGrid/imageGrid.py", line 102, in getOrientation
    return image._getexif()[274]
KeyError: 274

**Comment by wwwins** [comment]
This issue should be fixed with https://github.com/wwwins/ImageGridPython/commit/e2ee51be56160c42829591687a2eb86b5654f24c.
